DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  street VARCHAR(250) NOT NULL,
  zipcode VARCHAR(250) NOT NULL,
  city VARCHAR(250) NOT NULL,
  state CHAR(2) NOT NULL
);